// src/lib/mock-data.ts
import { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Kit de Balatas Cerámicas Delanteras',
    partNumber: 'BOS-BC1451',
    price: 1250.99,
    originalPrice: 1400.00,
    imageUrl: '/images/products/balatas.jpg', // Coloca tus imágenes en public/images/products/
    brand: 'Bosch',
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: '2',
    name: 'Amortiguador de Gas Trasero',
    partNumber: 'KYB-349108',
    price: 980.00,
    imageUrl: '/images/products/amortiguador.jpg',
    brand: 'KYB',
    isFeatured: true,
    isNew: true,
  },
  {
    id: '3',
    name: 'Bomba de Agua con Junta',
    partNumber: 'GAT-45006',
    price: 1800.50,
    imageUrl: '/images/products/bomba-agua.jpg',
    brand: 'Gates',
    isBestseller: true,
  },
  {
    id: '4',
    name: 'Filtro de Aceite Sintético',
    partNumber: 'FRA-XG7317',
    price: 250.00,
    imageUrl: '/images/products/filtro-aceite.jpg',
    brand: 'Fram',
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: '5',
    name: 'Kit de Afinación Completo Jetta A4',
    partNumber: 'MAN-AFIN-A4',
    price: 1100.00,
    imageUrl: '/images/products/kit-afinacion.jpg',
    brand: 'Mann-Filter',
    isNew: true,
  },
  {
    id: '6',
    name: 'Bujía de Iridio Laser',
    partNumber: 'NGK-IFR5E11',
    price: 350.00,
    imageUrl: '/images/products/bujia.jpg',
    brand: 'NGK',
    isNew: true,
  },
  {
    id: '7',
    name: 'Radiador de Aluminio',
    partNumber: 'TYC-13095',
    price: 2300.00,
    imageUrl: '/images/products/radiador.jpg',
    brand: 'TYC',
    isFeatured: true,
  },
  {
    id: '8',
    name: 'Sensor de Oxígeno (Sonda Lambda)',
    partNumber: 'DEN-234-4209',
    price: 1350.00,
    originalPrice: 1500.00,
    imageUrl: '/images/products/sensor-oxigeno.jpg',
    brand: 'Denso',
    isBestseller: true,
    isNew: true,
  },
];